import { MyForm } from "@/components/MyForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Form",
  description: "Generated by create next app",
};

export default function Form() {
  return <MyForm />;
}
