import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main className="p-10">
        <div className="flex flex-col">
          <h1 className="text-2xl font-bold">Home Page</h1>
          <Link href="/form">Redirect</Link>
        </div>
      </main>
    </>
  );
}
